package.path = './?.lua;./?/init.lua;'..package.path
local S = require('tests.support')
local total, failed = 0, 0
function test(name, fn)
  total=total+1
  local ok, err=pcall(fn)
  if ok then print('PASS '..name) else failed=failed+1; print('FAIL '..name..': '..tostring(err)) end
end
function eq(a,b) assert(a==b, 'expected '..tostring(b)..', got '..tostring(a)) end

test('config validates worker controller ID and timeout relationships', function()
  local C=require('autobuilder.config')
  local c=C.load({role='worker', controllerId=7})
  eq(c.controllerId,7)
  assert(not pcall(C.load,{role='worker'}))
  assert(not pcall(C.load,{heartbeatInterval=10,workerTimeout=5}))
  assert(not pcall(C.load,{role='other'}))
end)
test('checkpoints round trip and recover backup after corruption',function()
  local f=S.fs(); local c=require('autobuilder.core.checkpoint').new(f,S.codec(),'data/state')
  eq(c:load(),nil)
  assert(c:save({id=5,position={x=-10,y=64,z=2}}))
  assert(c:save({id=5,position={x=-9,y=64,z=2}}))
  eq(c:load().position.x,-9)
  f.files['data/state']='broken'
  local state, source=c:load(); eq(state.position.x,-10); assert(source:find('backup'))
end)
test('failed checkpoint promotion preserves last committed state',function()
  local f=S.fs(); local c=require('autobuilder.core.checkpoint').new(f,S.codec(),'state')
  assert(c:save({n=1})); f.fault.move='state'
  local ok,err=c:save({n=2}); assert(not ok and err)
  eq(c:load().n,1)
end)
test('corrupt existing checkpoint is not treated as first boot',function()
  local f=S.fs(); f.files.state='corrupt'
  local state,err=require('autobuilder.core.checkpoint').new(f,S.codec(),'state'):load()
  eq(state,nil); assert(err and err~='missing')
end)
test('logging filters levels and rotates bounded files',function()
  local f=S.fs(); local log=require('autobuilder.core.log').new(f,'log', {level='INFO',maxBytes=40,backups=2},function() return 0 end)
  assert(log:write('DEBUG','hidden')); eq(f.files.log,nil)
  for i=1,8 do assert(log:write('ERROR','disk problem '..i)) end
  assert(f.files.log and f.files['log.1']); eq(f.files['log.3'],nil)
end)
test('navigation updates only successful movement and respects north/east',function()
  local t=S.turtle(); local p={x=0,y=64,z=0,heading='north',known=true}
  local n=require('autobuilder.core.navigation').new(t,p,{minimumFuelReserve=0,movementRetries=2},function() return true end)
  assert(n:forward()); eq(p.z,-1)
  assert(n:turnRight()); eq(p.heading,'east'); assert(n:forward()); eq(p.x,1)
  t.blocked=true; assert(not n:up()); eq(p.y,64); eq(p.pending,nil)
end)
test('navigation refuses uncertain pose, protected coordinates and fuel exhaustion',function()
  local N=require('autobuilder.core.navigation'); local t=S.turtle()
  local p={x=0,y=64,z=0,heading='north',known=true,pending={action='forward'}}
  local n=N.new(t,p,{minimumFuelReserve=0},function() return true end)
  assert(not n:forward()); eq(t.calls,0)
  p.pending=nil; t.fuel=0; assert(not n:forward()); eq(t.calls,0)
  t.fuel=100
  n=N.new(t,p,{minimumFuelReserve=0,restrictedAreas={{min={x=0,y=64,z=-1},max={x=0,y=64,z=-1}}}},function() return true end)
  assert(not n:forward()); eq(t.calls,0)
end)
test('failed intent persistence never moves hardware',function()
  local t=S.turtle()
  local n=require('autobuilder.core.navigation').new(t,{x=0,y=0,z=0,heading='north',known=true},{minimumFuelReserve=0},function() return false,'disk full' end)
  assert(not n:forward()); eq(t.calls,0)
end)
test('GPS outage and exceptions return errors without losing local coordinates',function()
  local G=require('autobuilder.core.gps')
  local g=G.new({locate=function() return nil end},{timeout=1})
  local p,err=g:locate(); eq(p,nil); assert(err)
  g=G.new({locate=function() error('modem detached') end},{timeout=1})
  eq(g:locate(),nil)
  g=G.new({locate=function() return -1,64,3 end},{timeout=1})
  eq(g:locate().x,-1)
  eq(G.heading({x=0,y=4,z=0},{x=-1,y=4,z=0}),'west')
  eq(G.heading({x=0,y=4,z=0},{x=0,y=5,z=0}),nil)
end)

dofile('tests/exploration_jobs_test.lua')
dofile('tests/exploration_test.lua')
dofile('tests/exploration_protocol_test.lua')
dofile('tests/network_test.lua')
dofile('tests/runtime_test.lua')
dofile('tests/regression_test.lua')
dofile('tests/resources_test.lua')
dofile('tests/miner_test.lua')
dofile('tests/jobs_test.lua')
dofile('tests/mining_runtime_test.lua')
dofile('tests/install_test.lua')
dofile('tests/automation_test.lua')
dofile('tests/blueprint_test.lua')
dofile('tests/native_gzip_test.lua')
dofile('tests/chunks_test.lua')
dofile('tests/chunk_runtime_test.lua')
dofile('tests/pose_recovery_test.lua')
dofile('tests/pose_claims_test.lua')
dofile('tests/pose_probe_test.lua')
dofile('tests/native_schematic_test.lua')
dofile('tests/capacity_test.lua')
dofile('tests/home_return_test.lua')
dofile('tests/return_service_test.lua')
dofile('tests/logistics_nodes_test.lua')
dofile('tests/managed_logistics_test.lua')
dofile('tests/managed_logistics_runtime_test.lua')
dofile('tests/crafting_stations_test.lua')
dofile('tests/fuel_test.lua')
dofile('tests/fuel_service_test.lua')
dofile('tests/fuel_recovery_test.lua')
dofile('tests/fuel_courier_test.lua')
dofile('tests/fuel_rescue_service_test.lua')
dofile('tests/ledger_test.lua')
dofile('tests/providers_test.lua')
dofile('tests/production_test.lua')
dofile('tests/factory_setup_test.lua')
dofile('tests/construction_test.lua')
dofile('tests/project_runtime_test.lua')
dofile('tests/cathedral_test.lua')
dofile('tests/receipts_test.lua')
dofile('tests/automation_runtime_test.lua')
dofile('tests/renewables_test.lua')
dofile('tests/logistics_test.lua')
dofile('tests/parallel_mining_test.lua')
dofile('tests/logistics_runtime_test.lua')
dofile('tests/advanced_placement_test.lua')
dofile('tests/coordination_test.lua')
dofile('tests/cooperate_test.lua')
dofile('tests/infrastructure_test.lua')
dofile('tests/setup_test.lua')
dofile('tests/first_build_test.lua')
dofile('tests/site_test.lua')
dofile('tests/catalog_test.lua')

dofile('tests/autonomous_chain_test.lua')

if failed>0 then error(failed..' / '..total..' tests failed') end
print(total..' tests passed')
