#!/usr/bin/env python3
"""Generate GitHub release files or an offline computer root. Python stdlib only."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ROLES = ('controller', 'worker', 'miner', 'builder', 'logger', 'courier')
DEFAULT_BASE = 'https://raw.githubusercontent.com/USERNAME/REPOSITORY/main'
MODULES = ('sha256', 'manifest', 'io', 'transaction', 'manager', 'discovery', 'fleet', 'cli')


def base_url(url):
    url = url.rstrip('/')
    if not re.fullmatch(r'https://[\w.-]+/[\w./-]+', url, flags=re.ASCII) or any(
            part in ('.', '..') for part in url.split('/')[3:]):
        raise ValueError('Base must be an HTTPS raw repository directory without query/fragment')
    return url


def encoded(value):
    return (json.dumps(value, indent=2, sort_keys=True) + '\n').encode()


def atomic_write(path, data):
    fd, temporary = tempfile.mkstemp(prefix=path.name + '.', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write(data)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def bundle(root, base, recovery=False, fleet=False):
    parts = [
        '-- GENERATED by tools/release.py. Edit autobuilder/install/*.lua, then regenerate.\n',
        'local BASE_URL=' + json.dumps(base) + '\n',
        'local modules,loaded={},{}\nlocal require\n',
        'require=function(name)\n  if loaded[name]~=nil then return loaded[name] end\n',
        '  assert(modules[name],"Missing bundled module: "..name)\n',
        '  loaded[name]=modules[name](); return loaded[name]\nend\n',
    ]
    for name in (MODULES[:4] if recovery else MODULES):
        parts.append('modules["autobuilder.install.' + name + '"]=function()\n')
        parts.append((root / 'autobuilder/install' / (name + '.lua')).read_text())
        parts.append('\nend\n')
    if not recovery:
        for name in ('util', 'checkpoint', 'setup_state'):
            parts.append('modules["autobuilder.core.' + name + '"]=function()\n')
            parts.append((root / 'autobuilder/core' / (name + '.lua')).read_text())
            parts.append('\nend\n')
    if recovery:
        parts.append('local tx=require("autobuilder.install.transaction").new(fs,textutils)\n')
        parts.append('local recovered=tx:recover()\n')
        parts.append('print(recovered and "Installation recovered. Run reboot or retry update." or "No pending transaction.")\n')
    else:
        parts.append('local RECOVERY=' + json.dumps(bundle(root, base, recovery=True).decode(), ensure_ascii=False) + '\n')
        arguments = '{"fleet",table.unpack({...})}' if fleet else '{...}'
        parts.append('local environment=setmetatable({shell=shell},{__index=_G})\n')
        parts.append('return require("autobuilder.install.cli").run(' + arguments + ',environment,BASE_URL,RECOVERY)\n')
    return ''.join(parts).encode()


def file_roles(path):
    if path == 'autobuilder/controller.lua':
        return ['controller']
    if path in ('autobuilder/workers/worker.lua', 'autobuilder/pose.lua'):
        return list(ROLES[1:])
    # Shared runtime imports both controller and worker service modules.
    return list(ROLES)


def generate(root, base, version, check=False):
    root = Path(root)
    base = base_url(base)
    if not re.fullmatch(r'\d+\.\d+\.\d+', version, flags=re.ASCII) or len(version) > 30:
        raise ValueError('Version must be major.minor.patch')
    artifacts = {'installer.lua': bundle(root, base), 'fleet.lua': bundle(root, base, fleet=True)}
    paths = ['installer.lua', 'fleet.lua', 'update.lua', 'startup.lua']
    for path in sorted((root / 'autobuilder').rglob('*.lua')):
        relative = path.relative_to(root).as_posix()
        if relative == 'autobuilder/settings.lua' or any(
                part.startswith('.') for part in path.relative_to(root).parts):
            continue
        if relative.startswith(('autobuilder/data/', 'autobuilder/logs/')):
            continue
        paths.append(relative)
    files = []
    for path in sorted(paths):
        data = artifacts[path] if path in artifacts else (root / path).read_bytes()
        if not 0 < len(data) <= 1048576:
            raise ValueError('Invalid release file size: ' + path)
        files.append(dict(path=path, url=base + '/' + path, roles=file_roles(path),
                          version=version, bytes=len(data), sha256=hashlib.sha256(data).hexdigest()))
    manifest = dict(schema=1, project='autobuilder', version=version, baseUrl=base,
                    roles={role: dict(runtime='controller' if role == 'controller' else 'worker',
                                      status='available-mining-opt-in' if role in ('worker', 'miner') else 'available')
                           for role in ROLES}, files=files)
    artifacts['manifest.json'] = encoded(manifest)
    for name, data in artifacts.items():
        path = root / name
        if check:
            if not path.exists() or path.read_bytes() != data:
                raise ValueError(name + ' is stale; regenerate with tools/release.py')
        else:
            atomic_write(path, data)
    return manifest


def offline(root, output, role, controller_id=None):
    root, output = Path(root), Path(output)
    if output.exists():
        raise FileExistsError('Refusing to overwrite existing computer/output directory: ' + str(output))
    if role not in ROLES:
        raise ValueError('Unknown role: ' + role)
    if role != 'controller' and (type(controller_id) is not int or not 0 <= controller_id <= 2147483647):
        raise ValueError('Worker profiles require --controller with a nonnegative numeric computer ID')
    manifest = json.loads((root / 'manifest.json').read_text())
    generate(root, manifest['baseUrl'], manifest['version'], check=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix='.autobuilder-offline-', dir=output.parent))
    try:
        receipt = dict(schema=1, project='autobuilder', version=manifest['version'], role=role,
                       baseUrl=manifest['baseUrl'], files={})
        for entry in manifest['files']:
            if role not in entry['roles']:
                continue
            data = (root / entry['path']).read_bytes()
            if len(data) != entry['bytes'] or hashlib.sha256(data).hexdigest() != entry['sha256']:
                raise ValueError('Release changed during packaging: ' + entry['path'])
            dest = temporary / entry['path']
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
            receipt['files'][entry['path']] = {key: entry[key] for key in ('sha256', 'bytes', 'version')}
        config = ('-- Local configuration: normal updates preserve this file.\n'
                  '-- Configure hardware, GPS, depot and mining bounds before enabling mining.\n'
                  'return {\n  role = ' + json.dumps('controller' if role == 'controller' else 'worker') + ',\n')
        if role != 'controller':
            config += '  controllerId = ' + str(controller_id) + ',\n'
        capability = {'builder': 'building', 'logger': 'logging', 'courier': 'courier'}.get(role)
        if capability:
            config += '  automation = { ' + capability + ' = true },\n'
        config += '}\n'
        (temporary / 'autobuilder/settings.lua').write_text(config)
        (temporary / 'autobuilder/.installation.json').write_bytes(encoded(receipt))
        shutil.copyfile(root / 'manifest.json', temporary / 'manifest.json')
        if output.exists():
            raise FileExistsError('Output appeared while packaging: ' + str(output))
        temporary.rename(output)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)


def main():
    previous = json.loads((ROOT / 'manifest.json').read_text()) if (ROOT / 'manifest.json').exists() else {}
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base', default=previous.get('baseUrl', DEFAULT_BASE))
    parser.add_argument('--version', default=previous.get('version', '0.2.1'))
    parser.add_argument('--check', action='store_true', help='Fail if generated artifacts are stale; do not write')
    parser.add_argument('--offline', type=Path, help='Create a NEW directory ready to copy to a computer root')
    parser.add_argument('--role', choices=ROLES)
    parser.add_argument('--controller', type=int, help='Controller numeric computer ID for worker profiles')
    args = parser.parse_args()
    if args.offline and (not args.role or args.check):
        parser.error('--offline requires --role and cannot be combined with --check')
    if args.role and not args.offline:
        parser.error('--role is used with --offline')
    try:
        generate(ROOT, args.base, args.version, args.check)
        if args.offline:
            offline(ROOT, args.offline, args.role, args.controller)
            print('Offline computer root created at ' + str(args.offline))
        else:
            print('Release artifacts verified.' if args.check else 'Generated installer.lua and manifest.json.')
    except (OSError, ValueError) as exc:
        parser.exit(1, str(exc) + '\n')


if __name__ == '__main__':
    main()
